name: nightly

on: push

jobs:
  image:
    name: Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up qemu
        uses: docker/setup-qemu-action@v1
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: docker hub authentication
        uses: docker/login-action@v1
        with:
          username: figtive
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build and push
        if: ${{ startsWith(github.ref, 'refs/heads') }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          cache-from: figtive/gallery-api:nightly
          tags: |
            figtive/gallery-api:nightly
