name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  image:
    name: Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up qemu
        uses: docker/setup-qemu-action@v1
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: docker hub authentication
        uses: docker/login-action@v1
        with:
          username: figtive
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: parse semver string
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: provide env file
        run: echo "${{ secrets.ENV_FILE_RELEASE }}" > .env.production
      - name: build and push
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          cache-from: figtive/gallery-fe-v1:latest
          tags: |
            figtive/gallery-fe-v1:latest
            figtive/gallery-fe-v1:${{ steps.semver_parser.outputs.major }}
            figtive/gallery-fe-v1:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            figtive/gallery-fe-v1:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
